version: '3'

services:
  nginx:
    container_name: nginx
    build: requirements/nginx/.
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
    - inception
    volumes:
    - wordpress:/var/www/html 
    restart: always
 
  mariadb:
    container_name: mariadb
    expose:
      - "3306"
    build:       
      context: ./requirements/mariadb
      args:
        MDB_DATABASE: ${MDB_DATABASE}
        MDB_USER: ${MDB_USER}
        MDB_PASS: ${MDB_PASS}
        MDB_ROOT_PASS: ${MDB_ROOT_PASS}
    env_file: 
      - .env
    networks:
    - inception
    volumes:
      - mariadb:/var/lib/mysql
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
  image: wordpress
    env_file: .env
  depends_on:
    - mariadb
  restart: always
  networks:
    - inception
  volumes:
    - wp-volume:/var/www/wordpress

volumes:
#  wp-volume:
#    driver_opts:
#      o: bind
#      type: none
#      device: /home/${USER}/data/wordpress

  mariadb:
    driver_opts:
      o: bind
      type: none
      device: /home/msosnova/data/

networks:
  inception:

       
