version: '3'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
    - inception
    volumes:
    - wp-volume:/var/www/html 
    restart: always
 
  mariadb:
    container_name: mariadb
    expose:
      - "3306"
    build:       
      context: ./requirements/mariadb
      args:
        MDB_DATABASE: ${MDB_DATABASE}
        MDB_USER: ${MDB_ADMIN}
        MDB_PASS: ${MDB_PASS}
        MDB_ROOT_PASS: ${MDB_ROOT_PASS}
    env_file: 
      - .env
    networks:
    - inception
    volumes:
      - mdb-volume:/var/lib/mysql
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    expose:
      - "9000"
    build: ./requirements/wordpress
    env_file: .env
    depends_on:
      - mariadb
    restart: unless-stopped
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/wordpress
   

volumes:
  wp-volume:
    driver_opts:
      type: none
      o: bind
      device: /home/msosnova/data/wordpress
  mdb-volume:
    driver_opts:
      type: none
      o: bind
      device: /home/msosnova/data/mariadb

networks:
  inception:

